/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as SienteteComoEnCasaRouteImport } from './routes/sientete-como-en-casa'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as EdeenAirRouteImport } from './routes/edeen-air'
import { Route as CuidaTuRinconcitoRouteImport } from './routes/cuida-tu-rinconcito'
import { Route as CreativosRouteImport } from './routes/creativos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CafeteriaRouteImport } from './routes/cafeteria'
import { Route as BuyerPersonaRouteImport } from './routes/buyer-persona'
import { Route as IndexRouteImport } from './routes/index'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const SienteteComoEnCasaRoute = SienteteComoEnCasaRouteImport.update({
  id: '/sientete-como-en-casa',
  path: '/sientete-como-en-casa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const EdeenAirRoute = EdeenAirRouteImport.update({
  id: '/edeen-air',
  path: '/edeen-air',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidaTuRinconcitoRoute = CuidaTuRinconcitoRouteImport.update({
  id: '/cuida-tu-rinconcito',
  path: '/cuida-tu-rinconcito',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativosRoute = CreativosRouteImport.update({
  id: '/creativos',
  path: '/creativos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeteriaRoute = CafeteriaRouteImport.update({
  id: '/cafeteria',
  path: '/cafeteria',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerPersonaRoute = BuyerPersonaRouteImport.update({
  id: '/buyer-persona',
  path: '/buyer-persona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer-persona': typeof BuyerPersonaRoute
  '/cafeteria': typeof CafeteriaRoute
  '/contacto': typeof ContactoRoute
  '/creativos': typeof CreativosRoute
  '/cuida-tu-rinconcito': typeof CuidaTuRinconcitoRoute
  '/edeen-air': typeof EdeenAirRoute
  '/servicios': typeof ServiciosRoute
  '/sientete-como-en-casa': typeof SienteteComoEnCasaRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/stock': typeof StockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyer-persona': typeof BuyerPersonaRoute
  '/cafeteria': typeof CafeteriaRoute
  '/contacto': typeof ContactoRoute
  '/creativos': typeof CreativosRoute
  '/cuida-tu-rinconcito': typeof CuidaTuRinconcitoRoute
  '/edeen-air': typeof EdeenAirRoute
  '/servicios': typeof ServiciosRoute
  '/sientete-como-en-casa': typeof SienteteComoEnCasaRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/stock': typeof StockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer-persona': typeof BuyerPersonaRoute
  '/cafeteria': typeof CafeteriaRoute
  '/contacto': typeof ContactoRoute
  '/creativos': typeof CreativosRoute
  '/cuida-tu-rinconcito': typeof CuidaTuRinconcitoRoute
  '/edeen-air': typeof EdeenAirRoute
  '/servicios': typeof ServiciosRoute
  '/sientete-como-en-casa': typeof SienteteComoEnCasaRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/stock': typeof StockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer-persona'
    | '/cafeteria'
    | '/contacto'
    | '/creativos'
    | '/cuida-tu-rinconcito'
    | '/edeen-air'
    | '/servicios'
    | '/sientete-como-en-casa'
    | '/sobre-nosotros'
    | '/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyer-persona'
    | '/cafeteria'
    | '/contacto'
    | '/creativos'
    | '/cuida-tu-rinconcito'
    | '/edeen-air'
    | '/servicios'
    | '/sientete-como-en-casa'
    | '/sobre-nosotros'
    | '/stock'
  id:
    | '__root__'
    | '/'
    | '/buyer-persona'
    | '/cafeteria'
    | '/contacto'
    | '/creativos'
    | '/cuida-tu-rinconcito'
    | '/edeen-air'
    | '/servicios'
    | '/sientete-como-en-casa'
    | '/sobre-nosotros'
    | '/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerPersonaRoute: typeof BuyerPersonaRoute
  CafeteriaRoute: typeof CafeteriaRoute
  ContactoRoute: typeof ContactoRoute
  CreativosRoute: typeof CreativosRoute
  CuidaTuRinconcitoRoute: typeof CuidaTuRinconcitoRoute
  EdeenAirRoute: typeof EdeenAirRoute
  ServiciosRoute: typeof ServiciosRoute
  SienteteComoEnCasaRoute: typeof SienteteComoEnCasaRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sientete-como-en-casa': {
      id: '/sientete-como-en-casa'
      path: '/sientete-como-en-casa'
      fullPath: '/sientete-como-en-casa'
      preLoaderRoute: typeof SienteteComoEnCasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edeen-air': {
      id: '/edeen-air'
      path: '/edeen-air'
      fullPath: '/edeen-air'
      preLoaderRoute: typeof EdeenAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuida-tu-rinconcito': {
      id: '/cuida-tu-rinconcito'
      path: '/cuida-tu-rinconcito'
      fullPath: '/cuida-tu-rinconcito'
      preLoaderRoute: typeof CuidaTuRinconcitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creativos': {
      id: '/creativos'
      path: '/creativos'
      fullPath: '/creativos'
      preLoaderRoute: typeof CreativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafeteria': {
      id: '/cafeteria'
      path: '/cafeteria'
      fullPath: '/cafeteria'
      preLoaderRoute: typeof CafeteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-persona': {
      id: '/buyer-persona'
      path: '/buyer-persona'
      fullPath: '/buyer-persona'
      preLoaderRoute: typeof BuyerPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerPersonaRoute: BuyerPersonaRoute,
  CafeteriaRoute: CafeteriaRoute,
  ContactoRoute: ContactoRoute,
  CreativosRoute: CreativosRoute,
  CuidaTuRinconcitoRoute: CuidaTuRinconcitoRoute,
  EdeenAirRoute: EdeenAirRoute,
  ServiciosRoute: ServiciosRoute,
  SienteteComoEnCasaRoute: SienteteComoEnCasaRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
